language: php

php:
  - 7.0
  - 7.2

before_script:
  - 'php -r "echo ''PHP mem limit: ''.ini_get(''memory_limit'').PHP_EOL;"'
  - php -d memory_limit=-1 `which composer` install -n

script: phpunit -c app
