language: php

php:
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: dbname
  username: dbuser
  encoding: utf8

before_install:
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- export COMPOSER_MEMORY_LIMIT="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer --profile install -n
  - mysql -e 'create database dbname'

script:
  - phpunit -c app
