imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            
        console:
            type:   console
            bubble: false
            
        firephp:
            type:  firephp
            level: info

#assetic:
#    use_controller: true

# Swiftmailer Configuration
swiftmailer:
    transport:        '%mailer_transport%'
    host:             '%mailer_host%'
    username:         '%mailer_user%'
    password:         '%mailer_password%'
    delivery_address: '%mailer_delivery_address_dev%'
    spool:      { type: memory }
    disable_delivery: '%mailer_disable_delivery_dev%'

