#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        #Scheduler\SchBundle\Entity\User:
        #    algorithm:        sha1
        #    encode_as_base64: false
        #    iterations:       1

    role_hierarchy:
        ROLE_COACH:            ROLE_USER
        ROLE_REF:              ROLE_USER
        # old names
        ROLE_SCHEDULER:        ROLE_USER
        ROLE_ASSIGNER:         ROLE_USER
        ROLE_REF_ADMIN:        [ROLE_REF,ROLE_SCHEDULER,ROLE_ASSIGNER]
        # new names
        ROLE_REG_SCHEDULER:    ROLE_USER
        ROLE_REG_ASSIGNER:     ROLE_USER
        ROLE_REG_REF_ADMIN:    [ROLE_REF,ROLE_REG_SCHEDULER,ROLE_REG_ASSIGNER]
        ROLE_AREA_SCHEDULER:   ROLE_REG_SCHEDULER
        ROLE_AREA_ASSIGNER:    ROLE_REG_ASSIGNER
        ROLE_AREA_REF_ADMIN:   [ROLE_AREA_SCHEDULER,ROLE_AREA_ASSIGNER,ROLE_REF_ADMIN]
        ROLE_ADMIN:            [ROLE_AREA_SCHEDULER, ROLE_AREA_ASSIGNER, ROLE_AREA_REF_ADMIN]
        SUPER_ADMIN:           [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    #providers:
    #    administrators:
    #        entity: { class: SchedulerBundle:User }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    ~
            switch_user:  true
            logout_on_user_change: true

            remember_me:
#                #2.8 and higher secret: "%secret%"
                secret: '%secret%'
                lifetime: 2592000
                path: /
                domain: ~
#                #user_provider: fos_userbundle

        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #home:
        #    pattern:  ^/$
        #    security: false

        #unsecure_areas:
        #    pattern:  ^/(about|contact)$
        #    anonymous:    ~

        #login:
        #    pattern:  ^/login$
        #    security: false

        #secured_area:
        #    pattern:    ^/
        #    form_login:
        #        login_path:  /login
        #        check_path:  /login_check
        #    logout:
        #        path:   /logout
        #        target: /
        #    remember_me:
        #        key:      "oifjeqwoijfoqiejfopiweq"
        #        lifetime: 31536000 # 365 days in seconds
        #        path:     /
        #        domain:   ~ # Defaults to the current domain from $_SERVER
        #    #anonymous: ~

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/.*/show$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/offsch$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/offsch/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/offsch/reset$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/offsch2$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/coverage$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/export.csv, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game/assign/, roles: ROLE_REF }
        - { path: ^/game/scorecard/, roles: ROLE_REF }
        - { path: ^/game/delete$, roles: ROLE_ADMIN }
        - { path: ^/game/import$, roles: ROLE_AREA_SCHEDULER }
        - { path: ^/game/.*$, roles: ROLE_SCHEDULER }
        - { path: ^/team/refpntspublic, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/team/refpntspublic/breakdown, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/team/refpnts, roles: ROLE_REF }
        - { path: ^/team/refpnts/assign, roles: ROLE_REF }
        - { path: ^/team/refpnts/allrefs, roles: ROLE_REF }
        - { path: ^/team/refpnts/breakdown, roles: ROLE_REF }
        - { path: ^/team/import$, roles: ROLE_AREA_SCHEDULER }
        - { path: ^/team/.*/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/team, roles: ROLE_SCHEDULER }
        - { path: ^/location/redirect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/location/.*/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/location, roles: ROLE_SCHEDULER }
        - { path: ^/agegroup, roles: ROLE_AREA_SCHEDULER }
        - { path: ^/user/currentproject, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/project-game, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/project, roles: ROLE_ADMIN }
        - { path: ^/region, roles: ROLE_ADMIN }
        - { path: ^/mobileprovider, roles: ROLE_ADMIN }
        - { path: ^/message, roles: ROLE_ADMIN }



