<?php

namespace Scheduler\SchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
  public function findAllOrderedByName()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT p FROM SchedulerBundle:Location p ORDER BY p.name ASC')
      ->getResult();
  }

}
