<?php

namespace Scheduler\SchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogGameRepository extends EntityRepository
{
  public function findAllLogEntriesByGameId($gameid)
  {
    $q = "SELECT a FROM SchedulerBundle:LogGame a WHERE a.game_id = $gameid ORDER BY p.dt ASC";

    $result = $this->getEntityManager()
      ->createQuery($q)
      ->getResult();

    return $result;
  }

}
