<?php

namespace Scheduler\SchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffAssignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffAssignRepository extends EntityRepository
{
  public function findAssignmentsForGame()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT a FROM SchedulerBundle:OffAssign a ORDER BY a.date ASC')
      ->getResult();
  }
}
