<?php

namespace Scheduler\SchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
  public function findAllOrderedByName()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT p FROM SchedulerBundle:Region p ORDER BY p.name ASC')
      ->getResult();
  }

}
