<?php

namespace Scheduler\SchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
  public function findAllOrderedByName()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT p FROM SchedulerBundle:Team p ORDER BY p.name ASC')
      ->getResult();
  }

  public function findAllByProject($project)
  {
    $q = 'SELECT t FROM SchedulerBundle:Team t';
    if ($project) {
      $projectid = $project->getId();
      $q .= " WHERE t.project=$projectid";
    }
    $q .= ' ORDER BY t.name ASC, t.region ASC';
    return $this->getEntityManager()
      ->createQuery($q)
      ->getResult();
  }

  public function findAllByProjectAndRegion($project, $region)
  {
    if ($project && $region) {
      $projectid = $project->getId();
      $regionid = $region->getId();
      $q = 'SELECT t FROM SchedulerBundle:Team t' .
        " WHERE t.project=$projectid" .
        " AND t.region=$regionid" .
        ' ORDER BY t.name ASC';
      return $this->getEntityManager()
        ->createQuery($q)
        ->getResult();
    } else {
      return array();
    }
  }

}
